(function(){
  var A = window.Arena = window.Arena || {};

  function g(t, m, f){ return t.gender === 'chica' ? f : m; }
  function isKidOf(p, k){ return !!(k && k.baby && !p.baby && k.parents && k.parents.indexOf(p.id) !== -1); }

  A.ITEMS.anillo = { id: 'anillo', label: 'un anillo', short: 'el anillo', prop: 'ring' };
  A.ITEMS.dados = { id: 'dados', label: 'unos dados', short: 'los dados', prop: 'dice' };

  A.EVENTS = A.EVENTS.concat([

    /* ============ INTIMIDAD (todo insinuado) ============ */
    { k: 'cueva_pareja', n: 2, rel: 'lover', w: 9, type: 'romance', scene: 'cave', fx: 'fling',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se refugian en una cueva «para esperar a que pase la tormenta». No hay tormenta. La cueva tiembla un poco y los murciélagos se marchan, indignados.'; } },
    { k: 'tienda_pareja', n: 2, rel: 'lover', w: 9, type: 'romance', scene: 'cave', prop: 'tent', fx: 'fling',
      text: function(a, b){ return a.name + ' y ' + b.name + ' montan una tienda de campaña. La tienda no deja de moverse. Hay un viento muy localizado.'; } },
    { k: 'manta_pareja', n: 2, rel: 'lover', w: 5, type: 'romance', scene: 'cave', prop: 'tent', fx: 'fling',
      text: function(a, b){ return a.name + ' y ' + b.name + ' comparten una manta «por el frío». Hacen treinta grados. Nadie duerme mucho esa noche.'; } },
    { k: 'ligue_cueva', n: 2, rel: 'stranger', free: true, w: 5, type: 'romance', scene: 'cave', fx: 'love+fling',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se cruzan en una cueva. Se miran. Se hace un silencio muy largo. Nadie volverá a hablar de lo que pasa a continuación.'; } },
    { k: 'ligue_tienda', n: 2, rel: 'stranger', free: true, w: 4, type: 'romance', scene: 'cave', prop: 'tent', fx: 'love+fling',
      text: function(a, b){ return a.name + ' pide a ' + b.name + ' sitio en su tienda «porque llueve». Hace un sol espléndido. ' + b.name + ' dice que sí de todas formas.'; } },
    { k: 'aliados_derecho', n: 2, rel: 'ally', free: true, w: 8, type: 'romance', scene: 'cave', prop: 'tent', fx: 'love+fling',
      text: function(a, b){ return a.name + ' y ' + b.name + ' llevan una semana compartiendo tienda «solo como aliados». Esta noche se acaban las excusas.'; } },
    { k: 'buscar_bebe', n: 2, rel: 'lover', w: 7, type: 'romance', scene: 'cave', fx: 'tryBaby',
      text: function(a, b){ return a.name + ' y ' + b.name + ' hablan de tener un bebé. Lo hablan hasta que se dan cuenta de que están en una arena. Lo hacen igualmente.'; } },
    { k: 'cigueña', n: 2, rel: 'lover', w: 2, type: 'family', scene: 'birth', prop: 'stork', fx: 'stork',
      text: function(a, b, c, x){ return 'Una cigüeña sobrevuela a ' + a.name + ' y ' + b.name + ', deja caer un bebé con una nota que dice «no se admiten devoluciones» y se marcha. Ya son familia: se llama ' + x.baby.name + '.'; } },

    /* ============ PILLADOS ============ */
    { k: 'pillados_ruptura', n: 3, rel: 'group', w: 10, type: 'betrayal', scene: 'caught', fx: 'caughtbreak',
      cond: function(a, b, c){ return a.loverId === c.id && c.loverId === a.id && b.id !== c.id; },
      text: function(a, b, c){ return c.name + ' sale a buscar leña y encuentra a ' + a.name + ' con ' + b.name + ' en una situación que no tiene nada que ver con la leña. ' + c.name + ' suelta la leña, suelta una lágrima y se marcha. ' + a.name + ' y ' + b.name + ' ni se enteran.'; } },
    { k: 'pillados_almohadas', n: 3, rel: 'group', w: 8, type: 'fight', scene: 'caught', fx: 'breakupac',
      cond: function(a, b, c){ return a.loverId === c.id && c.loverId === a.id && b.id !== c.id; },
      text: function(a, b, c){ return c.name + ' pilla a ' + a.name + ' con ' + b.name + '. Se arma una pelea con almohadas, gritos y una cazuela. ' + b.name + ' huye en calzoncillos. Es el momento más humillante de la temporada.'; } },
    { k: 'pillados_venganza', n: 3, rel: 'group', w: 6, type: 'death', scene: 'caught', fx: 'kill_b_by_c+breakupac', req: { c: 'pistola' },
      cond: function(a, b, c){ return a.loverId === c.id && c.loverId === a.id && b.id !== c.id; },
      text: function(a, b, c){ return c.name + ' pilla a ' + a.name + ' con ' + b.name + ' y pierde los papeles: apunta con la pistola a ' + b.name + ' y dispara. ' + a.name + ' se queda con cara de «yo no he sido».'; },
      live: function(a, b, c){ return c.name + ' pilla a ' + a.name + ' con ' + b.name + ', saca la pistola y dispara. Falla. ' + b.name + ' sale corriendo en calzoncillos y no vuelve a mirar atrás.'; } },
    { k: 'pillados_trio', n: 3, rel: 'group', w: 5, type: 'alliance', scene: 'caught', fx: 'ally3',
      cond: function(a, b, c){ return a.loverId === c.id && c.loverId === a.id && b.id !== c.id; },
      text: function(a, b, c){ return c.name + ' pilla a ' + a.name + ' con ' + b.name + '. Se hace un silencio largo. «¿Hay sitio?», pregunta ' + c.name + '. Nace la alianza más rara de la arena.'; } },
    { k: 'pillados_chantaje', n: 3, rel: 'group', w: 7, type: 'theft', scene: 'steal', fx: 'steal3', req: { a: 'any' }, swap3: [2, 0, 1],
      cond: function(a, b, c){ return b.id !== c.id && a.id !== c.id; },
      text: function(a, b, c, x){ return c.name + ' pilla a ' + a.name + ' con ' + b.name + ' y promete guardar el secreto a cambio de ' + x.item.short + '. ' + a.name + ' paga sin rechistar.'; } },
    { k: 'pillados_rumor', n: 3, rel: 'group', w: 6, type: 'betrayal', scene: 'rumor', fx: 'breakupac', swap3: [2, 0, 1],
      cond: function(a, b, c){ return a.loverId === c.id && c.loverId === a.id && b.id !== c.id; },
      text: function(a, b, c){ return c.name + ' pilla a ' + a.name + ' con ' + b.name + ' y se lo cuenta a todo el bosque. Hasta las ardillas comentan el asunto. La pareja queda rota.'; } },
    { k: 'pillados_visita', n: 3, rel: 'group', w: 6, type: 'romance', scene: 'caught',
      cond: function(a, b, c){ return a.loverId === b.id && b.loverId === a.id && c.id !== a.id && c.id !== b.id; },
      text: function(a, b, c){ return c.name + ' pilla a ' + a.name + ' y ' + b.name + ' en plena intimidad. Se queda mirando un poco. Luego se marcha silbando y fingiendo que no ha visto nada.'; } },
    { k: 'pillados_aliados', n: 3, rel: 'group', w: 6, type: 'romance', scene: 'caught', fx: 'love+fling',
      cond: function(a, b, c){ return a.allies.indexOf(b.id) !== -1 && a.allies.indexOf(c.id) !== -1 && a.loverId !== b.id; },
      text: function(a, b, c){ return c.name + ' pilla a sus aliados ' + a.name + ' y ' + b.name + ' en la cueva. «¿Esto forma parte del plan?», pregunta. «Sí», responden los dos a la vez. No convence a nadie.'; } },

    /* ============ FAMILIA Y BEBÉS (nunca corren peligro) ============ */
    { k: 'fam_nana', n: 2, rel: 'family', family: true, w: 8, type: 'family', scene: 'nanny', prop: 'note',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return a.name + ' canta una nana a ' + b.name + '. ' + a.name + ' desafina; ' + b.name + ' llora aún más. Acaban durmiéndose los dos... y medio bosque.'; } },
    { k: 'fam_palabra', n: 2, rel: 'family', family: true, w: 6, type: 'family', scene: 'nanny', prop: 'heart',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return b.name + ' dice su primera palabra: «pistola». ' + a.name + ' no sabe si sentirse ' + g(a, 'orgulloso', 'orgullosa') + ' o preocupad' + g(a, 'o', 'a') + '.'; } },
    { k: 'fam_panal', n: 2, rel: 'family', family: true, w: 7, type: 'family', scene: 'nanny', prop: 'stink',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return a.name + ' cambia el pañal a ' + b.name + '. El olor derrite dos árboles y ahuyenta a un oso. Es el arma más eficaz de toda la arena.'; } },
    { k: 'fam_llanto', n: 2, rel: 'family', family: true, w: 7, type: 'family', scene: 'nanny', prop: 'cry',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return b.name + ' llora tan alto que se oye en toda la arena. ' + a.name + ' mece a ' + b.name + ' con desesperación mientras se acercan pasos. Falsa alarma: era una cabra.'; } },
    { k: 'fam_gatea', n: 2, rel: 'family', family: true, w: 6, type: 'family', scene: 'nanny', prop: 'crawl',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return b.name + ' empieza a gatear en dirección al precipicio. ' + a.name + ' persigue a ' + b.name + ' a cuatro patas, gritando. Final feliz. Sudor frío, pero feliz.'; } },
    { k: 'fam_pelo', n: 2, rel: 'family', family: true, w: 5, type: 'family', scene: 'nanny', prop: 'anger',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return b.name + ' tira a ' + a.name + ' del pelo. Fuerte. Muy fuerte. ' + a.name + ' jura que el bebé ha heredado el genio del otro progenitor.'; } },
    { k: 'fam_piedra', n: 2, rel: 'family', family: true, w: 5, type: 'family', scene: 'nanny', prop: 'heart',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return b.name + ' regala a ' + a.name + ' una piedra que ha encontrado. Es el mejor regalo que ' + a.name + ' ha recibido en su vida. Y el único.'; } },
    { k: 'fam_sonrisa', n: 2, rel: 'family', family: true, w: 5, type: 'family', scene: 'nanny', prop: 'heart',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return b.name + ' sonríe por primera vez. ' + a.name + ' llora de emoción. A lo lejos, un lobo llora también.'; } },
    { k: 'fam_diente', n: 2, rel: 'family', family: true, w: 4, type: 'family', scene: 'nanny', prop: 'anger',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return a.name + ' descubre que ' + b.name + ' ya tiene su primer diente. ' + b.name + ' lo estrena de inmediato mordiendo a un pato.'; } },
    { k: 'fam_biberon', n: 2, rel: 'family', family: true, w: 5, type: 'family', scene: 'nanny', prop: 'bottle',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return a.name + ' prepara un biberón con la última leche de cabra. ' + b.name + ' lo escupe. ' + a.name + ' llora más que ' + b.name + '.'; } },
    { k: 'fam_duerme', n: 2, rel: 'family', family: true, w: 5, type: 'family', scene: 'nanny', prop: 'zzz',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return b.name + ' se duerme por fin. ' + a.name + ' no se atreve ni a respirar. Un grillo empieza a cantar. ' + a.name + ' se plantea seriamente acabar con el grillo.'; } },
    { k: 'fam_regalo', n: 2, rel: 'family', family: true, w: 4, type: 'family', scene: 'nanny', prop: 'heart',
      cond: function(a, b){ return isKidOf(a, b); },
      text: function(a, b){ return 'Los patrocinadores envían un paracaídas con juguetes para ' + b.name + '. ' + a.name + ' se queda con el peluche; ' + b.name + ', con la caja. Todos contentos.'; } },
    { k: 'fam_foto', n: 3, rel: 'group', family: true, w: 8, type: 'family', scene: 'nanny', prop: 'photo',
      cond: function(a, b, c){ return isKidOf(a, c) && isKidOf(b, c); },
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y su bebé ' + c.name + ' se hacen una foto de familia con una piedra. Salen los tres con cara de no haber dormido en semanas.'; } },
    { k: 'fam_pañal_pelea', n: 3, rel: 'group', family: true, w: 6, type: 'family', scene: 'nanny', prop: 'stink',
      cond: function(a, b, c){ return isKidOf(a, c) && isKidOf(b, c); },
      text: function(a, b, c){ return a.name + ' y ' + b.name + ' discuten sobre a quién le toca cambiar el pañal a ' + c.name + '. Lo resuelve ' + c.name + ', con un método poco recomendable.'; } },
    { k: 'fam_paternidad', n: 3, rel: 'group', family: true, w: 6, type: 'family', scene: 'argue',
      cond: function(a, b, c){ return isKidOf(a, c) && !isKidOf(b, c) && a.loverId === b.id; },
      text: function(a, b, c){ return b.name + ' mira a ' + c.name + ' y pregunta a ' + a.name + ': «¿Seguro que es de los dos?». ' + a.name + ' no responde. Un grillo canta. Un largo, largo grillo.'; } },

    /* ============ SOLO: absurdos tranquilos ============ */
    { k: 'yoga', n: 1, rel: 'any', w: 5, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' intenta hacer yoga sobre un tronco. Consigue el «perro boca abajo» y no puede salir. Un perro de verdad observa la escena con pena.'; } },
    { k: 'bano_rio', n: 1, rel: 'any', w: 5, type: 'neutral', scene: 'bath',
      text: function(a){ return a.name + ' se da un baño en el río. Un pez le muerde donde más duele. Se oye el grito hasta la Cornucopia.'; } },
    { k: 'karaoke', n: 1, rel: 'any', w: 5, type: 'neutral', scene: 'karaoke',
      text: function(a){ return a.name + ' canta a pleno pulmón para animarse. Las aves huyen, un lobo aúlla y los patrocinadores bajan el volumen.'; } },
    { k: 'pescar', n: 1, rel: 'any', w: 5, type: 'item', scene: 'fish',
      text: function(a){ return a.name + ' pesca un pez enorme, que resulta ser una bota. Se la come igualmente.'; } },
    { k: 'cocinar', n: 1, rel: 'any', w: 5, type: 'neutral', scene: 'cook',
      text: function(a){ return a.name + ' cocina una sopa de piedras. Sale sorprendentemente buena. Las piedras, no tanto.'; } },
    { k: 'espejo', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' se mira en un charco y se piropea: «Qué ' + g(a, 'guapo', 'guapa') + ' estás». El charco no opina. Un pez, sí, y no le gusta lo que ve.'; } },
    { k: 'carta_madre', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' escribe una carta a su madre: «Querida mamá, aquí se está genial. Ayer casi me cae un piano». La mete en una botella y la tira al río.'; } },
    { k: 'amigo_piedra', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' entabla amistad con una piedra y la llama Roca. Es una buena oyente.'; } },
    { k: 'hormigas', n: 1, rel: 'any', w: 3, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' observa hormigas durante cuatro horas. Concluye que están mejor organizadas que todos los tributos juntos.'; } },
    { k: 'eco_cueva', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'hide',
      text: function(a){ return a.name + ' grita en una cueva: «¡Hola!». El eco responde con un insulto. ' + a.name + ' no lo esperaba.'; } },
    { k: 'sonambulo', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'sleep',
      text: function(a){ return a.name + ' camina ' + g(a, 'dormido', 'dormida') + ' toda la noche, cruza el campamento enemigo y vuelve a su cama. Nadie se atreve a despertar a ' + a.name + '.'; } },
    { k: 'monologo', n: 1, rel: 'any', w: 3, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' da un discurso a los árboles sobre el sentido de la vida. Un árbol se ríe. O es el viento.'; } },
    { k: 'hipo', n: 1, rel: 'any', w: 3, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' tiene hipo. Se oye a un kilómetro. Se esconde en un arbusto, pero el arbusto también tiene hipo.'; } },
    { k: 'rana', n: 1, rel: 'any', w: 3, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' besa una rana por si acaso. No pasa nada. La rana se siente ofendida.'; } },
    { k: 'cangrejo', n: 1, rel: 'any', w: 4, type: 'fight', scene: 'animal', prop: 'crab',
      text: function(a){ return 'Un cangrejo enorme pellizca a ' + a.name + ' donde no debería. ' + a.name + ' baila una danza de guerra durante un rato.'; } },
    { k: 'hallar_anillo', n: 1, rel: 'any', w: 4, type: 'item', scene: 'item', fx: 'get', it: 'anillo', req: { a: 'none' },
      text: function(a){ return a.name + ' encuentra un anillo dentro de un pez. Nadie sabe de quién es, pero quedaría bien en una boda.'; } },
    { k: 'hallar_dados', n: 1, rel: 'any', w: 4, type: 'item', scene: 'item', fx: 'get', it: 'dados', req: { a: 'none' },
      text: function(a){ return a.name + ' encuentra unos dados. Están trucados: siempre sale un seis. Es lo más parecido a la suerte que ha tenido en semanas.'; } },

    /* ============ SOLO: peligros con final cómico ============ */
    { k: 'abejas', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'bees',
      text: function(a){ return a.name + ' se topa con un panal gigante y decide llevarse un poco de miel. Las abejas tienen otras ideas.'; },
      live: function(a){ return a.name + ' se topa con un panal gigante. Las abejas persiguen a ' + a.name + ' hasta el río y le dejan la cara del tamaño de una sandía, pero sobrevive.'; } },
    { k: 'roca_rueda', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'boulder',
      text: function(a){ return 'Una roca gigante empieza a rodar hacia ' + a.name + ' como en las películas. ' + a.name + ' corre en la dirección equivocada.'; },
      live: function(a){ return 'Una roca gigante rueda hacia ' + a.name + ' como en las películas. ' + a.name + ' salta en el último segundo y la roca sigue su camino, tan tranquila.'; } },
    { k: 'ola', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'wave',
      text: function(a){ return 'Una ola gigante llega desde ninguna parte, en una arena sin mar, y se lleva a ' + a.name + '. Nadie pide explicaciones.'; },
      live: function(a){ return 'Una ola gigante llega desde ninguna parte y empapa a ' + a.name + ' de la cabeza a los pies. Al menos, hoy no hace falta ducharse.'; } },
    { k: 'volcan', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'volcano',
      text: function(a){ return a.name + ' asa nubes de azúcar en la boca de un volcán. El volcán, que llevaba siglos dormido, se despierta de mal humor.'; },
      live: function(a){ return a.name + ' asa nubes de azúcar en un volcán. Erupciona un poco, pero solo lo justo para chamuscar el flequillo.'; } },
    { k: 'tornado', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'tornado',
      text: function(a){ return 'Un tornado pequeño, pero muy convencido, recoge a ' + a.name + ' y se lleva a ' + a.name + ' de paseo. Nadie sabe adónde.'; },
      live: function(a){ return 'Un tornado pequeño se lleva el sombrero de ' + a.name + ' y nada más. ' + a.name + ' nunca había tenido tanta suerte.'; } },
    { k: 'cohete', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'launch', prop: 'rocket',
      text: function(a){ return a.name + ' se ata un cohete de fuegos artificiales a la espalda «para llegar antes». Llega mucho antes. A la luna, concretamente.'; },
      live: function(a){ return a.name + ' se ata un cohete de fuegos artificiales a la espalda. Sale volando, da tres vueltas y aterriza en un charco. Ahora huele a pólvora, pero está bien.'; } },
    { k: 'tabla_roca', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'launch', prop: 'seesaw',
      text: function(a){ return a.name + ' se sienta en un extremo de una tabla apoyada en una roca. Del cielo cae otra roca en el otro extremo. ' + a.name + ' sale volando hacia el horizonte.'; },
      live: function(a){ return a.name + ' se sienta en una tabla. Cae una roca en el otro extremo y sale volando... directo a un arbusto blando. Un aterrizaje de diez.'; } },
    { k: 'aguila', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'snatch',
      text: function(a){ return 'Un águila confunde a ' + a.name + ' con un conejo y se lleva a ' + a.name + ' por los aires. Se oye un «¡ay!» que se aleja poco a poco.'; },
      live: function(a){ return 'Un águila intenta llevarse a ' + a.name + ', pero pesa demasiado. Suelta a ' + a.name + ' a un metro del suelo y se marcha ofendida.'; } },
    { k: 'jabon', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'slip', prop: 'soap',
      text: function(a){ return a.name + ' se lava con una pastilla de jabón a orillas del río. Se le escapa, la pisa y sale volando. La pastilla se queda tan limpia.'; },
      live: function(a){ return a.name + ' pisa una pastilla de jabón y se desliza por la orilla como un pingüino. Acaba en el río, pero ' + g(a, 'muy limpio', 'muy limpia') + ': un éxito.'; } },
    { k: 'cocodrilo', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'animal', prop: 'croc',
      text: function(a){ return a.name + ' cruza un río sin fijarse en el tronco que tiene ojos. El tronco tenía hambre.'; },
      live: function(a){ return a.name + ' cruza un río y pisa un tronco con ojos. El tronco bosteza, se lo piensa y se vuelve a dormir.'; } },
    { k: 'espejismo', n: 1, rel: 'any', w: 3, type: 'death', fx: 'die_a', scene: 'trap',
      text: function(a){ return a.name + ' ve un oasis en el desierto y corre hacia él. Era un pozo profundo con dibujo de oasis.'; },
      live: function(a){ return a.name + ' ve un oasis y corre hacia él. Era un espejismo, pero a un metro había un charco de verdad. Casi lo mismo.'; } },

    /* ============ DÚOS: desconocidos ============ */
    { k: 'discusion_norte', n: 2, rel: 'stranger', w: 5, type: 'fight', scene: 'argue',
      text: function(a, b){ return a.name + ' y ' + b.name + ' discuten por dónde está el norte. Ninguno tiene brújula. Ninguno cede. Los dos acaban yendo hacia el sur.'; } },
    { k: 'cotilleo', n: 2, rel: 'stranger', w: 5, type: 'alliance', scene: 'rumor', fx: 'ally',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se sientan a criticar a los demás tributos. Se lo pasan tan bien que acaban siendo aliados.'; } },
    { k: 'apuesta', n: 2, rel: 'stranger', w: 5, type: 'neutral', scene: 'gamble',
      text: function(a, b){ return a.name + ' y ' + b.name + ' apuestan a ver quién aguanta más sin parpadear. Pasan seis horas. Ambos se quedan sin ojos... metafóricamente. Empatan.'; } },
    { k: 'apuesta_objeto', n: 2, rel: 'stranger', w: 6, type: 'theft', scene: 'gamble', fx: 'steal', req: { b: 'any' },
      text: function(a, b, c, x){ return a.name + ' gana a ' + b.name + ' a los dados y se queda con ' + x.item.short + '. ' + b.name + ' jura que los dados estaban trucados. Lo estaban, pero por ' + a.name + '.'; } },
    { k: 'chantaje', n: 2, rel: 'stranger', w: 5, type: 'theft', scene: 'steal', fx: 'steal', req: { b: 'any' },
      text: function(a, b, c, x){ return a.name + ' chantajea a ' + b.name + ' con haberle visto llorar de madrugada. ' + b.name + ' entrega ' + x.item.short + ' sin discutir.'; } },
    { k: 'beso_robado', n: 2, rel: 'stranger', free: true, w: 4, type: 'romance', scene: 'love', fx: 'love',
      text: function(a, b){ return a.name + ' da un beso robado a ' + b.name + ' y sale corriendo. ' + b.name + ' se queda pensando: ha sido un robo, sí, pero de los buenos.'; } },
    { k: 'carta_amor', n: 2, rel: 'stranger', free: true, w: 4, type: 'romance', scene: 'gift', prop: 'letter', fx: 'love',
      text: function(a, b){ return a.name + ' deja una carta de amor en la mochila de ' + b.name + ', escrita con zumo de mora. ' + b.name + ' la lee y sonríe. No entiende ni una palabra, pero sonríe.'; } },
    { k: 'manzana', n: 2, rel: 'stranger', w: 5, type: 'death', fx: 'kill_b', scene: 'poison', prop: 'apple',
      text: function(a, b){ return a.name + ' regala una manzana a ' + b.name + ' «sin ninguna razón». La manzana estaba envenenada, como las de los cuentos.'; },
      live: function(a, b){ return a.name + ' regala una manzana a ' + b.name + '. ' + b.name + ' la rechaza: es alérgic' + g(b, 'o', 'a') + ' a las frutas... y a los regalos sospechosos.'; } },
    { k: 'trampa_propia', n: 2, rel: 'stranger', w: 5, type: 'death', fx: 'die_a', scene: 'trap',
      text: function(a, b){ return a.name + ' cava un hoyo trampa para ' + b.name + '. ' + b.name + ' se lo avisa con educación. ' + a.name + ' no le cree y cae dentro.'; },
      live: function(a, b){ return a.name + ' cava un hoyo trampa para ' + b.name + ' y cae dentro. ' + b.name + ' ayuda a ' + a.name + ' a salir con una cuerda y una sonrisa incómoda.'; } },
    { k: 'empujon', n: 2, rel: 'stranger', w: 4, type: 'death', fx: 'kill_b', scene: 'fall',
      text: function(a, b){ return a.name + ' empuja a ' + b.name + ' por un barranco «sin querer». Tres veces.'; },
      live: function(a, b){ return a.name + ' empuja a ' + b.name + ' por un barranco «sin querer». ' + b.name + ' se agarra de milagro a una rama y dedica a ' + a.name + ' una mirada asesina.'; } },
    { k: 'reto_oso', n: 2, rel: 'stranger', w: 5, type: 'death', fx: 'die_b', scene: 'animal', prop: 'bear',
      text: function(a, b){ return a.name + ' reta a ' + b.name + ' a abrazar a un oso. ' + b.name + ' acepta por orgullo. El orgullo se queda en el suelo.'; },
      live: function(a, b){ return a.name + ' reta a ' + b.name + ' a abrazar a un oso. ' + b.name + ' acepta, y el oso devuelve el abrazo y regala miel a ' + b.name + '. Se hacen amigos.'; } },
    { k: 'presentacion', n: 2, rel: 'stranger', w: 4, type: 'alliance', scene: 'handshake', fx: 'ally',
      text: function(a, b){ return a.name + ' se presenta a ' + b.name + ' con una reverencia. ' + b.name + ' responde con otra, más profunda. Acaban aliados por buena educación.'; } },
    { k: 'quimica', n: 2, rel: 'stranger', free: true, w: 4, type: 'romance', scene: 'love', fx: 'love',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se pelean por el mismo tronco, el mismo río y el mismo bocadillo. Al final se dan cuenta de que tienen los mismos gustos. Y el mismo destino.'; } },

    /* ============ DÚOS: aliados ============ */
    { k: 'abrazo', n: 2, rel: 'ally', w: 6, type: 'alliance', scene: 'hug',
      text: function(a, b){ return a.name + ' abraza a ' + b.name + ' sin motivo. ' + b.name + ' se queda rígid' + g(b, 'o', 'a') + '. El abrazo dura tres minutos. Es el mejor abrazo de la temporada.'; } },
    { k: 'confesion', n: 2, rel: 'ally', free: true, w: 5, type: 'romance', scene: 'love', fx: 'love',
      text: function(a, b){ return a.name + ' confiesa a ' + b.name + ' que siempre le ha gustado. ' + b.name + ' confiesa que también. Los dos confiesan que no saben si es amor o hambre.'; } },
    { k: 'plan_secreto', n: 2, rel: 'ally', w: 4, type: 'neutral', scene: 'rumor',
      text: function(a, b){ return a.name + ' y ' + b.name + ' apuntan su plan secreto en un papel. El viento se lo lleva directo a las manos de otro tributo.'; } },
    { k: 'duo_karaoke', n: 2, rel: 'ally', w: 4, type: 'alliance', scene: 'karaoke',
      text: function(a, b){ return a.name + ' y ' + b.name + ' cantan a dúo. Suenan peor que por separado, pero se lo pasan mejor.'; } },
    { k: 'duo_cocina', n: 2, rel: 'ally', w: 4, type: 'alliance', scene: 'cook',
      text: function(a, b){ return a.name + ' y ' + b.name + ' cocinan juntos. Uno corta, el otro remueve, los dos discuten y la cena sale increíble. Nadie pregunta de qué es.'; } },
    { k: 'duo_pesca', n: 2, rel: 'ally', w: 4, type: 'alliance', scene: 'fish',
      text: function(a, b){ return a.name + ' y ' + b.name + ' pescan juntos en silencio durante horas. No pican peces, pero se sienten más unidos que nunca.'; } },
    { k: 'clase_baile', n: 2, rel: 'ally', w: 4, type: 'alliance', scene: 'dance',
      text: function(a, b){ return a.name + ' enseña a ' + b.name + ' a bailar. ' + b.name + ' tiene dos pies izquierdos. Uno de ellos, el de ' + a.name + '.'; } },
    { k: 'pelea_manta', n: 2, rel: 'ally', w: 5, type: 'fight', scene: 'brawl', fx: 'unally',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se pelean por la única manta. Al final la manta se rompe y la alianza también.'; } },
    { k: 'sacrificio', n: 2, rel: 'ally', w: 4, type: 'death', fx: 'die_a', scene: 'animal', prop: 'bear',
      text: function(a, b){ return a.name + ' se sacrifica para distraer a un oso mientras ' + b.name + ' huye. ' + b.name + ' mira hacia atrás, llora... y sigue corriendo.'; },
      live: function(a, b){ return a.name + ' se sacrifica para distraer a un oso. El oso resulta ser un disfraz de otro tributo, que se quita la cabeza y se disculpa.'; } },
    { k: 'ronda_historias', n: 2, rel: 'ally', w: 4, type: 'neutral', scene: 'campfire',
      text: function(a, b){ return a.name + ' cuenta a ' + b.name + ' un chiste. No tiene gracia. ' + b.name + ' se ríe tanto que se le escapa un resoplido que espanta a un ciervo.'; } },

    /* ============ DÚOS: pareja ============ */
    { k: 'pedida_anillo', n: 2, rel: 'lover', w: 8, type: 'romance', scene: 'wedding', req: { a: 'anillo' },
      text: function(a, b){ return a.name + ' se arrodilla ante ' + b.name + ' con un anillo de verdad. ' + b.name + ' dice que sí. La arena entera aplaude, aunque la mitad son ardillas.'; } },
    { k: 'divorcio', n: 2, rel: 'lover', w: 4, type: 'romance', scene: 'split', fx: 'breakup',
      text: function(a, b){ return a.name + ' y ' + b.name + ' firman el divorcio sobre una hoja. Llevaban juntos cuatro días. Se reparten la tienda y la custodia de la ardilla.'; } },
    { k: 'terapia', n: 2, rel: 'lover', w: 4, type: 'romance', scene: 'awkward',
      text: function(a, b){ return a.name + ' y ' + b.name + ' van a terapia de pareja con una ardilla. La ardilla no da consejos, pero escucha muy bien.'; } },
    { k: 'discusion_pareja', n: 2, rel: 'lover', w: 5, type: 'romance', scene: 'argue', fx: 'breakup',
      text: function(a, b){ return a.name + ' y ' + b.name + ' discuten por quién aprieta el tubo de pasta de dientes por el medio. Ni siquiera hay pasta de dientes en la arena. La pareja se rompe igual.'; } },
    { k: 'abrazo_pareja', n: 2, rel: 'lover', w: 5, type: 'romance', scene: 'hug',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se abrazan tan fuerte que se olvidan de que están en una arena. Un pájaro les hace una foto.'; } },
    { k: 'cena_pareja', n: 2, rel: 'lover', w: 4, type: 'romance', scene: 'cook',
      text: function(a, b){ return a.name + ' cocina para ' + b.name + ' su plato estrella: nada con sal. ' + b.name + ' dice que está riquísimo. Es una mentira preciosa.'; } },

    /* ============ TRÍOS ============ */
    { k: 'botella', n: 3, rel: 'group', w: 4, type: 'romance', scene: 'gamble',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' juegan a la botella. Sale un beso, una discusión y una botella rota. La botella no vuelve a hablar.'; } },
    { k: 'motin_cocina', n: 3, rel: 'group', w: 4, type: 'fight', scene: 'brawl',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' votan quién cocina. Empatan a un voto. Lo deciden con una pelea de barro. Cocina el barro.'; } },
    { k: 'oso_trio', n: 3, rel: 'group', w: 5, type: 'death', fx: 'die_c', scene: 'animal', prop: 'bear',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' huyen de un oso. Para salvarse no hay que correr más que el oso, sino más que ' + c.name + '.'; },
      live: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' huyen de un oso. Los tres corren tan rápido que el oso se cansa, se sienta y se echa a llorar.'; } },
    { k: 'puente_roto', n: 3, rel: 'group', w: 4, type: 'death', fx: 'die_c', scene: 'fall',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' cruzan un puente de cuerda. El puente aguanta a dos. Los tres son tres.'; },
      live: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' cruzan un puente de cuerda. Cruje, cruje y cruje... pero aguanta. Nadie mira hacia abajo.'; } },
    { k: 'cuentacuentos', n: 3, rel: 'group', w: 4, type: 'neutral', scene: 'campfire',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' se cuentan historias de miedo alrededor del fuego. La más terrorífica es la de ' + c.name + ': trata de un examen de matemáticas.'; } },
    { k: 'trio_karaoke', n: 3, rel: 'group', w: 4, type: 'neutral', scene: 'karaoke',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' montan un karaoke con una piña de micrófono. Cantan «Bohemian Rhapsody» a tres voces. Ninguna es la correcta.'; } }
  ]);
})();
