(function(){
  var A = window.Arena = window.Arena || {};

  function g(t, m, f){ return t.gender === 'chica' ? f : m; }

  // n: nº de personajes. rel: stranger | ally | lover | group | any. free: nadie tiene pareja viva.
  // fx: none | love | breakup | ally | ally3 | unally | unally3 | die_a|b|c | kill_a|b|c | kill_b_unally
  //   die_x = muere x (accidente). kill_x = muere x y el primero de los demás suma una baja.
  // swap: en la escena el orden es [b, a, c] (para que quien ataca salga a la izquierda).
  A.EVENTS = [

    /* ---------- SOLO, tranquilos ---------- */
    { k: 'arbol', n: 1, rel: 'any', w: 6, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' pasa media hora hablando con un árbol. El árbol no responde, pero ' + a.name + ' siente que ha habido conexión.'; } },
    { k: 'fuego', n: 1, rel: 'any', w: 6, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' lleva tres horas intentando encender fuego con dos palos. Al final se rinde y se come los palos.'; } },
    { k: 'calcetin', n: 1, rel: 'any', w: 5, type: 'item', scene: 'item', prop: 'crate',
      text: function(a){ return a.name + ' abre una caja misteriosa. Dentro hay otra caja. Dentro de esa, otra más. En la última, un calcetín. ' + a.name + ' decide que es su calcetín de la suerte.'; } },
    { k: 'baile', n: 1, rel: 'any', w: 6, type: 'neutral', scene: 'dance',
      text: function(a){ return a.name + ' improvisa un baile de la victoria sin haber ganado nada. Se ha adelantado, pero se le ve feliz.'; } },
    { k: 'arbusto_doble', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'hide',
      text: function(a){ return a.name + ' se esconde en un arbusto que ya estaba ocupado por otro tributo. Se miran. Ninguno dice nada. Pasan toda la noche así.'; } },
    { k: 'sombra', n: 1, rel: 'any', w: 5, type: 'neutral', scene: 'injured',
      text: function(a){ return a.name + ' tropieza con su propia sombra. Lo único que sale herido es el orgullo.'; } },
    { k: 'ardilla', n: 1, rel: 'any', w: 5, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' se ha hecho ' + g(a, 'amigo', 'amiga') + ' de una ardilla. La ardilla ya ha dado su opinión sobre los demás tributos: no es buena.'; } },
    { k: 'ukelele', n: 1, rel: 'any', w: 5, type: 'item', scene: 'item', prop: 'crate',
      text: function(a){ return 'Un patrocinador envía a ' + a.name + ' un paracaídas con un ukelele. ' + a.name + ' toca fatal, pero con muchísimo sentimiento.'; } },
    { k: 'pato_persigue', n: 1, rel: 'any', w: 6, type: 'fight', scene: 'animal', prop: 'duck',
      text: function(a){ return 'Un pato de aspecto muy agresivo persigue a ' + a.name + ' toda la tarde. ' + a.name + ' sobrevive, pero con el orgullo hecho trizas.'; } },
    { k: 'roca', n: 1, rel: 'any', w: 5, type: 'neutral', scene: 'hide',
      text: function(a){ return a.name + ' pasa la noche fingiendo ser una roca. Un lobo se acerca, lo piensa mucho y se marcha.'; } },
    { k: 'cofre', n: 1, rel: 'any', w: 4, type: 'item', scene: 'item', prop: 'chest',
      text: function(a){ return a.name + ' encuentra un cofre lleno de oro. Es completamente inútil en la arena, pero se lo lleva igualmente.'; } },
    { k: 'rio', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' descubre que el río baja cuesta abajo. ' + g(a, 'Inspirado', 'Inspirada') + ', decide seguirlo. Es una decisión brillante y nadie sabe por qué.'; } },
    { k: 'barro', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'injured',
      text: function(a){ return a.name + ' se cae en un charco de barro y decide que, a partir de ahora, será un espíritu del pantano.'; } },
    { k: 'cactus', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'injured',
      text: function(a){ return a.name + ' intenta abrazar un cactus creyendo que era un tributo con la piel sensible. Era un cactus. ' + a.name + ' aprende la lección.'; } },
    { k: 'bateria', n: 1, rel: 'any', w: 4, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' mira el móvil cada cinco minutos, sin batería y sin cobertura, por si acaso.'; } },
    { k: 'nubes', n: 1, rel: 'any', w: 3, type: 'neutral', scene: 'explore',
      text: function(a){ return a.name + ' pasa la tarde buscando formas en las nubes. Todas parecen una patata. Todas.'; } },

    /* ---------- SOLO, mortales (con salvación cómica) ---------- */
    { k: 'platano', n: 1, rel: 'any', w: 6, type: 'death', fx: 'die_a', scene: 'slip',
      text: function(a){ return a.name + ' pisa una cáscara de plátano, sale volando, da tres vueltas en el aire y aterriza de cabeza. Los patrocinadores lloran de risa. ' + a.name + ' no se levanta.'; },
      live: function(a){ return a.name + ' pisa una cáscara de plátano, sale volando y aterriza en un charco de barro. Lo mejor es que lo ha visto medio mundo.'; } },
    { k: 'piano', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'drop', prop: 'piano',
      text: function(a){ return 'Un piano cae del cielo sobre ' + a.name + '. Nadie sabe de dónde ha salido. Suena un último acorde, desafinado.'; },
      live: function(a){ return 'Un piano se estrella a un palmo de ' + a.name + ', que se limita a decir «guau».'; } },
    { k: 'yunque', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'drop', prop: 'anvil',
      text: function(a){ return 'Un yunque cae sobre ' + a.name + '. Un clásico que nunca falla.'; },
      live: function(a){ return 'Un yunque cae al lado de ' + a.name + ', que lo mira un rato y decide que ya es hora de replantearse su vida.'; } },
    { k: 'meteorito', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'drop', prop: 'meteor',
      text: function(a){ return 'Un meteorito cae sobre ' + a.name + '. La arena no tenía presupuesto para esto, y aun así.'; },
      live: function(a){ return 'Un meteorito pasa rozando a ' + a.name + ' y le chamusca las cejas. Es lo más emocionante que le ha pasado en años.'; } },
    { k: 'rayo', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'lightning',
      text: function(a){ return 'Un rayo cae sobre ' + a.name + ' justo cuando decía «a mí no me pasa nada».'; },
      live: function(a){ return 'Un rayo cae sobre ' + a.name + ', que sale con el pelo de punta y cara de haber visto a Dios, pero con vida.'; } },
    { k: 'selfie', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'fall',
      text: function(a){ return a.name + ' retrocede para hacerse un selfie perfecto con el atardecer. El precipicio también sale en la foto. ' + a.name + ' no llegará a verla.'; },
      live: function(a){ return a.name + ' casi se cae por un precipicio haciéndose un selfie. Se salva ' + g(a, 'agarrado', 'agarrada') + ' a una rama, sin soltar el móvil. Prioridades.'; } },
    { k: 'seta', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'poison', prop: 'mushroom',
      text: function(a){ return a.name + ' se come una seta de colores porque tenía muy buena pinta. Lo último que ve son peces bailando en el cielo.'; },
      live: function(a){ return a.name + ' se come una seta de colores y pasa la noche hablando con los peces del cielo. Al amanecer está perfectamente y algo más sabio.'; } },
    { k: 'oso', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'animal', prop: 'bear',
      text: function(a){ return a.name + ' intenta abrazar a un oso para hacerse su amigo. El oso acepta el abrazo... y a ' + a.name + ' como cena.'; },
      live: function(a){ return 'Un oso se acerca a ' + a.name + ', se lo piensa un momento y se marcha decepcionado. ' + a.name + ' no sabe si sentirse ' + g(a, 'aliviado', 'aliviada') + ' o ' + g(a, 'insultado', 'insultada') + '.'; } },
    { k: 'pato_final', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'animal', prop: 'duck',
      text: function(a){ return 'Un pato de aspecto inofensivo persigue a ' + a.name + ' hasta un barranco. Después mira al cielo y grazna una sola vez. El pato ha ganado.'; },
      live: function(a){ return 'Un pato persigue a ' + a.name + ' por el bosque. ' + a.name + ' logra escapar, pero el pato no olvida.'; } },
    { k: 'trampilla', n: 1, rel: 'any', w: 5, type: 'death', fx: 'die_a', scene: 'trap',
      text: function(a){ return 'El suelo se abre bajo ' + a.name + ' y aparece un cartel: «Trampa. Gracias por participar».'; },
      live: function(a){ return 'El suelo se abre bajo ' + a.name + ', pero cae sobre un colchón. Algún patrocinador quiere que ' + a.name + ' siga en juego... por ahora.'; } },
    { k: 'arenas', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'trap',
      text: function(a){ return a.name + ' se hunde en unas arenas movedizas mientras da un discurso motivacional sobre no rendirse. No se rinde. Se hunde igualmente.'; },
      live: function(a){ return a.name + ' cae en arenas movedizas, pero se agarra a un patito de goma que pasaba por allí. Un milagro con plumas.'; } },
    { k: 'estornudo', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'fall',
      text: function(a){ return a.name + ' estornuda tan fuerte que sale volando hacia atrás, choca con un árbol y no vuelve a despertar.'; },
      live: function(a){ return a.name + ' estornuda tan fuerte que sale volando hacia atrás y aterriza en un arbusto. Se ha quedado sin moco, pero con vida.'; } },
    { k: 'risa', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'ghost',
      text: function(a){ return a.name + ' se ríe tanto de su propio chiste que se atraganta con un caramelo. Muere haciendo lo que amaba: reírse de ' + g(a, 'sí mismo', 'sí misma') + '.'; },
      live: function(a){ return a.name + ' se ríe tanto de su propio chiste que se atraganta, pero un buen golpe de tos despeja la situación. El chiste seguía siendo malo.'; } },
    { k: 'tarta', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'feast',
      text: function(a){ return a.name + ' se come tanta tarta que estalla. Metafóricamente. Pero también un poco literalmente.'; },
      live: function(a){ return a.name + ' se come tanta tarta que tiene que echarse una siesta de doce horas. Es la mejor decisión de la temporada.'; } },
    { k: 'globo', n: 1, rel: 'any', w: 4, type: 'death', fx: 'die_a', scene: 'balloon',
      text: function(a){ return a.name + ' se ata a un globo para ver la arena desde arriba. El globo tiene otros planes y se marcha con ' + a.name + ' fuera del mapa. Fuera de la arena, fuera de juego.'; },
      live: function(a){ return a.name + ' se ata a un globo para ver la arena desde arriba. El globo explota a los diez metros. La caída es corta y blanda.'; } },

    /* ---------- DÚOS entre desconocidos ---------- */
    { k: 'violines', n: 2, rel: 'stranger', free: true, w: 6, type: 'romance', scene: 'love', fx: 'love',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se encuentran en un claro. Se miran. Suena una música de violines que nadie sabe de dónde viene. Es amor.'; } },
    { k: 'charco', n: 2, rel: 'stranger', free: true, w: 5, type: 'romance', scene: 'love', fx: 'love',
      text: function(a, b){ return a.name + ' y ' + b.name + ' beben del mismo charco, se rozan las manos sin querer y ya no hay marcha atrás.'; } },
    { k: 'vida_pasada', n: 2, rel: 'stranger', free: true, w: 5, type: 'romance', scene: 'love', fx: 'love',
      text: function(a, b){ return a.name + ' pregunta a ' + b.name + ': «¿Nos conocemos de algo?». «De otra vida», responde ' + b.name + '. Y así empieza todo.'; } },
    { k: 'pistola_sorpresa', n: 2, rel: 'stranger', w: 6, type: 'death', fx: 'kill_b', scene: 'shoot',
      text: function(a, b){ return a.name + ' sale de un arbusto con una pistola, grita «¡sorpresa!» y dispara a ' + b.name + '. Fin de la fiesta.'; },
      live: function(a, b){ return a.name + ' sale de un arbusto con una pistola, grita «¡sorpresa!» y dispara... a otro arbusto. ' + b.name + ' aplaude por educación.'; } },
    { k: 'pistola_agua', n: 2, rel: 'stranger', w: 5, type: 'death', fx: 'kill_b', scene: 'shoot',
      text: function(a, b){ return a.name + ' apunta a ' + b.name + ' con una pistola de agua para gastarle una broma. Lo que nadie sabía es que estaba llena de ácido.'; },
      live: function(a, b){ return a.name + ' apunta a ' + b.name + ' con una pistola de agua. Solo era agua. Los dos se ríen y se hacen un poco amigos.'; } },
    { k: 'devolver_pistola', n: 2, rel: 'stranger', w: 4, type: 'death', fx: 'kill_b', scene: 'shoot',
      text: function(a, b){ return b.name + ' pide a ' + a.name + ' que le devuelva la pistola que se ha «tomado prestada». ' + a.name + ' la devuelve. Con una bala.'; },
      live: function(a, b){ return b.name + ' pide a ' + a.name + ' que le devuelva la pistola. ' + a.name + ' se la devuelve por el cañón. Mala idea, pero nadie se dispara.'; } },
    { k: 'platano_pelea', n: 2, rel: 'stranger', w: 5, type: 'death', fx: 'kill_b', scene: 'brawl',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se pelean por el último plátano. Gana ' + a.name + ', y ' + b.name + ' se queda sin plátano y sin vida.'; },
      live: function(a, b){ return a.name + ' y ' + b.name + ' se pelean por el último plátano. Lo pierden en el barro y se lo come un mono. El mono es el único ganador.'; } },
    { k: 'calcetinazos', n: 2, rel: 'stranger', w: 5, type: 'fight', scene: 'brawl',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se pelean a calcetinazos. Nadie gana. Ambos huelen peor.'; } },
    { k: 'saludo', n: 2, rel: 'stranger', w: 5, type: 'neutral', scene: 'awkward',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se cruzan y se saludan educadamente con la cabeza. Hasta en la arena hay modales.'; } },
    { k: 'sarten', n: 2, rel: 'stranger', w: 5, type: 'fight', scene: 'pan',
      text: function(a, b){ return a.name + ' golpea a ' + b.name + ' con una sartén. Suena un «boing» de dibujos animados. ' + b.name + ' cae redondo, pero se levanta con la cabeza hecha un timbre.'; } },
    { k: 'sarten_letal', n: 2, rel: 'stranger', w: 4, type: 'death', fx: 'kill_b', scene: 'pan',
      text: function(a, b){ return a.name + ' golpea a ' + b.name + ' con una sartén con tan mala suerte que ' + b.name + ' no vuelve a levantarse. La sartén sale indemne.'; },
      live: function(a, b){ return a.name + ' golpea a ' + b.name + ' con una sartén. Suena un «boing» de dibujos animados y ' + b.name + ' se queda mirando los pajaritos un buen rato.'; } },
    { k: 'piedra_papel', n: 2, rel: 'stranger', w: 4, type: 'death', fx: 'kill_a', swap: true, scene: 'brawl',
      text: function(a, b){ return a.name + ' y ' + b.name + ' resuelven sus diferencias a piedra, papel y tijera. ' + a.name + ' saca papel. ' + b.name + ' saca una piedra... directa a la cabeza de ' + a.name + '.'; },
      live: function(a, b){ return a.name + ' y ' + b.name + ' resuelven sus diferencias a piedra, papel y tijera. Empatan catorce veces. Se acaba la tarde y se dan la mano.'; } },
    { k: 'club', n: 2, rel: 'stranger', w: 5, type: 'alliance', scene: 'handshake', fx: 'ally',
      text: function(a, b){ return a.name + ' y ' + b.name + ' deciden fundar un club de supervivencia. Se pelean por el nombre durante una hora, pero acaban siendo aliados.'; } },
    { k: 'bocadillo', n: 2, rel: 'stranger', w: 5, type: 'alliance', scene: 'handshake', fx: 'ally',
      text: function(a, b){ return a.name + ' ofrece a ' + b.name + ' la mitad de su bocadillo a cambio de un pacto de no agresión. ' + b.name + ' acepta. El bocadillo ya estaba mordido, pero es una tregua.'; } },

    /* ---------- DÚOS de aliados ---------- */
    { k: 'estrellas', n: 2, rel: 'ally', free: true, w: 6, type: 'romance', scene: 'love', fx: 'love',
      text: function(a, b){ return a.name + ' y ' + b.name + ' miran las estrellas. Uno dice «qué noche tan bonita». El otro responde «tú también». Silencio. Ya no hay vuelta atrás.'; } },
    { k: 'abrazo_cuchillo', n: 2, rel: 'ally', w: 6, type: 'death', fx: 'kill_b_unally', scene: 'stab',
      text: function(a, b){ return a.name + ' abraza a ' + b.name + ' con muchísimo cariño y le clava un cuchillo por la espalda. Fue un abrazo precioso, en serio.'; },
      live: function(a, b){ return a.name + ' intenta clavar un cuchillo por la espalda a ' + b.name + ', pero se le engancha la manga. Se hace el loco. La alianza queda algo tocada.'; } },
    { k: 'pistola_aliado', n: 2, rel: 'ally', w: 6, type: 'death', fx: 'kill_b_unally', scene: 'shoot',
      text: function(a, b){ return a.name + ' apunta con una pistola a ' + g(b, 'su mejor aliado', 'su mejor aliada') + ' y dice: «Esto no es personal». Es muy personal.'; },
      live: function(a, b){ return a.name + ' apunta con una pistola a ' + b.name + ' y dice «esto no es personal», pero la pistola hace «clic». ' + b.name + ' ya está corriendo.'; } },
    { k: 'sopa', n: 2, rel: 'ally', w: 5, type: 'death', fx: 'kill_b', scene: 'poison', prop: 'bottle',
      text: function(a, b){ return a.name + ' prepara la cena para ' + b.name + '. «¿Por qué brilla la sopa?», pregunta ' + b.name + '. «Son especias», responde ' + a.name + '.'; },
      live: function(a, b){ return a.name + ' prepara una sopa que brilla en la oscuridad para ' + b.name + '. ' + b.name + ' repite tres veces. Tiene un estómago de acero.'; } },
    { k: 'cosquillas', n: 2, rel: 'ally', w: 4, type: 'death', fx: 'die_b', scene: 'fall',
      text: function(a, b){ return a.name + ' hace cosquillas a ' + b.name + ' para animar el ambiente. ' + b.name + ' se ríe tanto que se cae por un barranco.'; },
      live: function(a, b){ return a.name + ' hace cosquillas a ' + b.name + ', que se ríe tan fuerte que espanta a un oso. Resultado positivo para todos.'; } },
    { k: 'mosca', n: 2, rel: 'ally', w: 4, type: 'death', fx: 'kill_b', scene: 'stab',
      text: function(a, b){ return a.name + ' intenta espantar una mosca del hombro de ' + b.name + ' con un hacha. Ha dado a la mosca. Y a ' + b.name + '.'; },
      live: function(a, b){ return a.name + ' intenta espantar una mosca del hombro de ' + b.name + ' con un hacha. Falla por un pelo. La mosca se ríe. ' + b.name + ' sale corriendo un rato.'; } },
    { k: 'venta', n: 2, rel: 'ally', w: 4, type: 'alliance', scene: 'split', fx: 'unally',
      text: function(a, b){ return a.name + ' vende a ' + b.name + ' a cambio de un cupón de descuento de la tienda de regalos de la arena. Se acabó la alianza.'; } },
    { k: 'discusion_comida', n: 2, rel: 'ally', w: 4, type: 'alliance', scene: 'split', fx: 'unally',
      text: function(a, b){ return a.name + ' y ' + b.name + ' discuten por quién ha comido más. Se declara la guerra fría. Alianza disuelta.'; } },
    { k: 'saludo_secreto', n: 2, rel: 'ally', w: 5, type: 'alliance', scene: 'handshake',
      text: function(a, b){ return a.name + ' y ' + b.name + ' inventan un saludo secreto de catorce pasos. Lo repiten cada mañana. Nadie más lo entiende ni lo entenderá.'; } },
    { k: 'turno_vigilancia', n: 2, rel: 'ally', w: 4, type: 'neutral', scene: 'hide',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se turnan para vigilar. ' + a.name + ' se duerme en su turno. ' + b.name + ' también. Sobreviven de milagro.'; } },

    /* ---------- DÚOS de pareja ---------- */
    { k: 'ukelele_amor', n: 2, rel: 'lover', w: 5, type: 'romance', scene: 'love',
      text: function(a, b){ return a.name + ' dedica a ' + b.name + ' una canción de amor con un ukelele que ha encontrado. Suena fatal. ' + b.name + ' llora. De emoción, se supone.'; } },
    { k: 'foto_pareja', n: 2, rel: 'lover', w: 4, type: 'romance', scene: 'love',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se hacen una foto de pareja con una piedra en lugar del móvil. Salen guapísimos.'; } },
    { k: 'boda', n: 2, rel: 'lover', w: 5, type: 'romance', scene: 'wedding',
      text: function(a, b){ return a.name + ' pide matrimonio a ' + b.name + ' con un anillo hecho con una hoja. ' + b.name + ' dice que sí. Al fondo, un pájaro llora.'; } },
    { k: 'beso_lluvia', n: 2, rel: 'lover', w: 5, type: 'romance', scene: 'love',
      text: function(a, b){ return a.name + ' y ' + b.name + ' se besan bajo la lluvia. A diez metros cae un rayo. Ninguno se da cuenta.'; } },
    { k: 'celos', n: 2, rel: 'lover', w: 5, type: 'romance', scene: 'split', fx: 'breakup',
      text: function(a, b){ return a.name + ' descubre que ' + b.name + ' ha estado cinco minutos hablando con otro tributo. Escena de celos monumental. ' + b.name + ' dormirá esta noche en un arbusto. La pareja queda rota.'; } },
    { k: 'celos_disparo', n: 2, rel: 'lover', w: 4, type: 'death', fx: 'kill_b', scene: 'shoot',
      text: function(a, b){ return a.name + ' dispara a ' + b.name + ' por «haberse comido el último plátano». Ambos acabarán arrepintiéndose. Bueno, uno de ellos.'; },
      live: function(a, b){ return a.name + ' dispara a ' + b.name + ' por «haberse comido el último plátano», pero falla. Se quedan mirando. Se piden perdón. Comparten el plátano que no existe.'; } },
    { k: 'flecha', n: 2, rel: 'lover', w: 4, type: 'death', fx: 'die_a', scene: 'mourn',
      text: function(a, b){ return a.name + ' se lanza delante de ' + b.name + ' para protegerle de una flecha. La flecha no iba hacia ' + b.name + ': iba hacia un pájaro. Pero ' + a.name + ' ya estaba en el aire.'; },
      live: function(a, b){ return a.name + ' se lanza delante de ' + b.name + ' para protegerle de una flecha. La flecha rebota en la cabeza de ' + a.name + '. Nunca se sabrá por qué.'; } },
    { k: 'tronco', n: 2, rel: 'lover', w: 4, type: 'death', fx: 'die_a', scene: 'drop', prop: 'rock',
      text: function(a, b){ return a.name + ' graba «' + a.name + ' + ' + b.name + '» en un tronco. El tronco, harto de tanta cursilería, cae sobre ' + a.name + '.'; },
      live: function(a, b){ return a.name + ' graba «' + a.name + ' + ' + b.name + '» en un tronco. El tronco se cae, pero a un lado. Es una señal del universo. O eso quieren creer.'; } },

    /* ---------- TRÍOS ---------- */
    { k: 'banda', n: 3, rel: 'group', w: 6, type: 'alliance', scene: 'dance', fx: 'ally3',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' fundan una banda para animar el campamento. Se llaman «Los Supervivientes de Nadie». Suenan horrible y nadie se atreve a decírselo.'; } },
    { k: 'fiesta_sorpresa', n: 3, rel: 'group', w: 5, type: 'death', fx: 'kill_c', scene: 'drop', prop: 'bomb',
      text: function(a, b, c){ return a.name + ' y ' + b.name + ' organizan una fiesta sorpresa para ' + c.name + '. Los globos eran explosivos. Feliz cumpleaños, ' + c.name + '.'; },
      live: function(a, b, c){ return a.name + ' y ' + b.name + ' organizan una fiesta sorpresa para ' + c.name + '. Los globos eran explosivos, pero solo salió confeti. Los tres lloran de risa.'; } },
    { k: 'cartas', n: 3, rel: 'group', w: 5, type: 'death', fx: 'kill_c', scene: 'fall',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' juegan a las cartas para decidir quién cocina. ' + c.name + ' hace trampas. ' + a.name + ' y ' + b.name + ' le expulsan de la partida... y de un acantilado.'; },
      live: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' juegan a las cartas para decidir quién cocina. ' + c.name + ' hace trampas y acaba cocinando toda la semana.'; } },
    { k: 'nombre_grupo', n: 3, rel: 'group', w: 4, type: 'alliance', scene: 'split', fx: 'unally3',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' pasan tres horas debatiendo el nombre del grupo. Se separan sin llegar a un acuerdo.'; } },
    { k: 'barbacoa', n: 3, rel: 'group', w: 5, type: 'neutral', scene: 'feast',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' encuentran una barbacoa abandonada. Comen y echan una siesta colectiva. La arena está preocupantemente en paz.'; } },
    { k: 'rayo_grupo', n: 3, rel: 'group', w: 4, type: 'death', fx: 'die_c', scene: 'lightning',
      text: function(a, b, c){ return 'Un rayo cae sobre ' + a.name + ', ' + b.name + ' y ' + c.name + '. Solo ' + c.name + ' llevaba un paraguas de metal.'; },
      live: function(a, b, c){ return 'Un rayo cae sobre ' + a.name + ', ' + b.name + ' y ' + c.name + '. Los tres salen despeinados y con la sensación de que el pelo no volverá a ser el mismo.'; } },
    { k: 'triangulo', n: 3, rel: 'group', w: 4, type: 'romance', scene: 'love',
      text: function(a, b, c){ return a.name + ' y ' + b.name + ' se enamoran a la vez de ' + c.name + '. ' + c.name + ' intenta hacer las presentaciones y provoca el caos. Nadie resuelve nada.'; } },
    { k: 'coreografia', n: 3, rel: 'group', w: 4, type: 'neutral', scene: 'dance',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' improvisan una coreografía. Nadie la grabará, y aun así lo dan todo.'; } },
    { k: 'pistola_trio', n: 3, rel: 'group', w: 4, type: 'death', fx: 'die_c', scene: 'shoot',
      text: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' se pelean por una pistola. Al forcejear se dispara sola y acierta a ' + c.name + '.'; },
      live: function(a, b, c){ return a.name + ', ' + b.name + ' y ' + c.name + ' se pelean por una pistola. Al forcejear se dispara sola y le da a un árbol. El árbol no dice nada.'; } }
  ];
})();
